
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { StaffDatabase } from '@/types/staff';

const SUPABASE_URL = "https://oyicyfsffdcigzdaertj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aWN5ZnNmZmRjaWd6ZGFlcnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODUxMDgsImV4cCI6MjA1OTA2MTEwOH0.Rwm_E6pX8D2UoNEmPRtMO-JwONF32qInQeXxoaMYSvI";

export const staffSupabase = createClient<StaffDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
